project:
  type: website

website:
  title: "Gregory's Blog"
  site-url: https://dreamcorestudios.com
  description: "This is Albert Rapp's personal Blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: theme.scss

editor: visual

