project:
  type: website
  output-dir: docs

website:
  title: "Gregory's Blog"
  site-url: https://glizcorp.com
  description: "This is Gregory's Personal Blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: zephyr

editor: visual

